python EventWeighting.py --samples 364701 --eventWeight weight --outName PtWeight --jettype LCTopo --etaLow 1.3 --etaHigh 1.8
python EventWeighting.py --samples 364702 --eventWeight weight --outName PtWeight --jettype LCTopo --etaLow 1.3 --etaHigh 1.8
python EventWeighting.py --samples 364703 --eventWeight weight --outName PtWeight --jettype LCTopo --etaLow 1.3 --etaHigh 1.8
python EventWeighting.py --samples 364704 --eventWeight weight --outName PtWeight --jettype LCTopo --etaLow 1.3 --etaHigh 1.8
python EventWeighting.py --samples 364705 --eventWeight weight --outName PtWeight --jettype LCTopo --etaLow 1.3 --etaHigh 1.8
python EventWeighting.py --samples 364706 --eventWeight weight --outName PtWeight --jettype LCTopo --etaLow 1.3 --etaHigh 1.8
python EventWeighting.py --samples 364707 --eventWeight weight --outName PtWeight --jettype LCTopo --etaLow 1.3 --etaHigh 1.8
python EventWeighting.py --samples 364708 --eventWeight weight --outName PtWeight --jettype LCTopo --etaLow 1.3 --etaHigh 1.8
python EventWeighting.py --samples 364709 --eventWeight weight --outName PtWeight --jettype LCTopo --etaLow 1.3 --etaHigh 1.8
python EventWeighting.py --samples 364710 --eventWeight weight --outName PtWeight --jettype LCTopo --etaLow 1.3 --etaHigh 1.8
python EventWeighting.py --samples 364711 --eventWeight weight --outName PtWeight --jettype LCTopo --etaLow 1.3 --etaHigh 1.8
python EventWeighting.py --samples 364712 --eventWeight weight --outName PtWeight --jettype LCTopo --etaLow 1.3 --etaHigh 1.8